# Site settings
title: Excapes
email: contact@excapes.tv
description: Excapes es una web-serie de viajes. 
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://excapes.tv" # the base hostname & protocol for your site
twitter_username: excapes.twitter
facebook_username:  excapes.facebook
instagram_username: excapes.instagram
youtube_username: excapes.youtube
counter: '0'

# Build settings
markdown: kramdown


collections:
  - episodes
  - destinations
  - challenges
  - sponsors