# Site settings
title: Excapes
email: contacto@excapes.tv
description: Excapes es una serie web y una guía de viajes que te ayuda a descubrir lugares increíbles de México, te ofrece promociones exclusivas para tus viajes y te invita a que participes en sus capítulos.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://excapes.tv" # the base hostname & protocol for your site
twitter_username: #excapes.twitter
facebook_username:  #excapes.facebook
instagram_username: excapes.tv
youtube_username: playlist?list=PLa3oL93O2Vq4_6vjuK9b93GQEz4y4VC4o

# Build settings
markdown: kramdown


collections:
  - episodes
  - destinations
  - sponsors
