# Site settings
title: Excapes
email: contacto@excapes.tv
description: Excapes.tv es una web-serie y una guía para viajeros que busca inspirarte a conocer México y llevar tu experiencia al extremo.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://excapes.tv" # the base hostname & protocol for your site
twitter_username: #excapes.twitter
facebook_username:  #excapes.facebook
instagram_username: excapes.tv
youtube_username: playlist?list=PLa3oL93O2Vq4_6vjuK9b93GQEz4y4VC4o

# Build settings
markdown: kramdown


collections:
  - episodes
  - destinations
  - sponsors
